spring:
  application:
    name: gateway-servic
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                      name: AUTH-SERVICE
                      fallbackUri: forward:/fallback/auth

            - id: employee-service
              uri: lb://EMPLOYEE-SERVICE
              predicates:
                - Path=/api/employees/**
              filters:
                - AuthFilter
                - name: CircuitBreaker
                  args:
                      name: EMPLOYEE-SERVICE
                      fallbackUri: forward:/fallback/employee

            - id: address-service
              uri: lb://ADDRESS-SERVICE
              predicates:
                - Path=/api/address/**
              filters:
                - AuthFilter
                - name: CircuitBreaker
                  args:
                      name: ADDRESS-SERVICE
                      fallbackUri: forward:/fallback/address

resilience4j:
  timelimiter:
    instances:
      AUTH-SERVICE:
        timeoutDuration: 5s
      EMPLOYEE-SERVICE:
        timeoutDuration: 5s
      ADDRESS-SERVICE:
        timeoutDuration: 5s

  circuitbreaker:
    instances:
      AUTH-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3

      EMPLOYEE-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3

      ADDRESS-SERVICE:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 6s
        automaticTransitionFromOpenToHalfOpenEnabled: true
        permittedNumberOfCallsInHalfOpenState: 3

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents
  health:
    circuitbreakers:
      enabled: true


server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

jwt:
  secret: 9f3c7a1d6e2b8c4f5a7d9e1b3c6f8a2d4e7c1b5f9a3d6e8c2f4b7a1d5e9c3f6
  expiration: 86400000