spring:
  application:
    name: employee-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true         # crash ngay nếu không connect được Config Server
      retry:
          max-attempts: 6        # thử tối đa 6 lần
          initial-interval: 1500 # lần đầu chờ 1.5 giây
          max-interval: 3000     # chờ tối đa 3 giây mỗi lần
          multiplier: 1.5        # mỗi lần chờ lâu hơn 1.5x

management:
  endpoints:
    web:
      exposure:
        include: refresh, health