spring:
  application:
    name: address-service
  config:
    import: "configserver:http://localhost:8888"
  cloud:
    config:
      fail-fast: true         # crash ngay nếu không connect được Config Server
      retry:
        max-attempts: 6
        initial-interval: 1500
        max-interval: 3000
        multiplier: 1.5

management:
  endpoints:
    web:
      exposure:
        include: refresh, health